#!/bin/bash

#Copyright 2015 Julian Sax
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

printhelp() {
    echo "$0 [OPTIONS] DRIVE"
    echo "Eject SCSI/SATA/SAS drive for safe remove"
    echo ""
    echo "Options:"
    echo "  -h   --help     Show this help"
    echo "  -f   --force    Force ejecting even when volumes are mounted"
    echo "  -v   --verbose  Be verbose"
    echo "  -u   --unmount  Automatically unmount mounted volumes"
    echo "       --version  Show version"
    echo "You can not combine options like -fvu (yet)!"
}

#check if help is needed
if [ "$1" = "--help" -o "$1" = "-h" ]
then
    printhelp
    exit
fi

#check if user wants version
if [ "$1" = "--version" ]
then
    echo "sataeject 0.1"
fi

#no arguments -> print help
if [ $# -eq 0 ]
then
    printhelp
    exit
fi

#some vars with standard values
verbose=0
force=0
unmount=0
device=null

#go through arguments and fill vars
for i in $@
do
    char1=$(expr substr $i 1 1)
    if [ "$char1" = "-" ]
    then
	option=$i
	if [ "$option" = "-f" -o "$option" = "--force" ]
	then
	    force=1

	elif [ "$option" = "-v" -o "$option" = "--verbose" ]
	then
	    verbose=1

	elif [ "$option" = "-u" -o "$option" = "--unmount" ]
	then
	    unmount=1

	else
	    echo "Unknown option: $option"
	    printhelp
	    exit
	fi
    else
	device=$i
	break
    fi
done

#no device specified
if [ "$device" = "null" ]
then
    echo "You have to specify a drive to eject!"
    printhelp
    exit
fi

#check if file is a device
if [ -b $device ]
then
    if [ $verbose -eq 1 ]
    then
	echo "Found device $device"
    fi
else
    echo "There is no device $device!"
    exit
fi

#check if device starts with "sd" (maybe there is a better way to do it)
if [ "$(expr substr $device 6 2)" = "sd" ]
then
    name=$(expr substr $device 6 4)
else
    echo "This seems not to be a SATA/SCSI/SAS drive!"
    exit
fi

#check if file is longer than sdx (here could also be a better way)
if [ "$(expr substr $device 9 1)" != "" ]
then
    echo "You have to specify a whole drive and not a partition!"
    exit
fi

#check for mounted devices and perform according to the provided options
if [ "$(cat /proc/mounts | grep $device)" != "" ]
then
    if [ $unmount -eq 0 -a $force -eq 0 ]
    then
	echo "There are partitions still mounted."
	echo "Use either -u option to automatically unmount or -f to ignore (not recommended)."
	exit
    elif [ $unmount -eq 0 -a $force -eq 1 ]
    then
	if [ $verbose -eq 1 ]
	then
	    echo "There are partitions still mounted. Ignoring."
	fi
    elif [ $unmount -eq 1 ]
    then
	if [ $verbose -eq 1 ]
	then
	    echo "Unmounting mounted partitions..."
	fi
	stage1=$(cat /proc/mounts | grep $device)
	for i in $stage1
	do
	    if [ "$(expr substr $i 1 7)" = "/dev/sd" ]
	    then
		if [ $verbose -eq 1 ]
		then
		    echo "Unmounting $i..."
		fi
		umount $i
	    fi
	done
	if [ "$(cat /proc/mounts | grep $device)" != "" ]
	then
	    if [ $force -eq 0 ]
	    then
	       echo "Could not unmount all partitions. Exiting."
	       exit
	    else
		if [ $verbose -eq 1 ]
		then
		    echo "Could not unmount all partitions. Ignoring."
		fi
	    fi
	fi
    fi
fi

sync

#finally ejecting the drive. Phew!
if [ $verbose -eq 1 ]
then
   echo "Ejecting $device..."
fi
echo 1 > /sys/class/block/$name/device/delete
if [ $verbose -eq 1 ]
then
    echo "Done."
fi
